import * as z from "zod";
import {
  ToolStatus,
  ToolTier,
  DeploymentType,
  BusinessSize,
  SupportChannel,
  PricingModel,
  LearningFormat,
  SkillLevel,
  ProviderType,
} from "~/.generated/prisma/browser";

import {
  createSearchParamsCache,
  createStandardSchemaV1,
  parseAsArrayOf,
  parseAsInteger,
  parseAsString,
  parseAsStringEnum,
  parseAsBoolean,
} from "nuqs/server";
import { type Brokers } from "~/.generated/prisma/browser";
import { getSortingStateParser } from "~/lib/parsers";

export const brokerListParams = {
  broker_name: parseAsString.withDefault(""),
  sort: getSortingStateParser<Brokers>().withDefault([
    { id: "createdAt", desc: true },
  ]),
  page: parseAsInteger.withDefault(1),
  perPage: parseAsInteger.withDefault(25),
  from: parseAsString.withDefault(""),
  to: parseAsString.withDefault(""),
  operator: parseAsStringEnum(["and", "or"]).withDefault("and"),
  status: parseAsArrayOf(
    parseAsStringEnum(Object.values(ToolStatus)),
  ).withDefault([]),
  type: parseAsString,
  beginner_friendly: parseAsBoolean,
};

export const brokerListSchema = createStandardSchemaV1(brokerListParams);
export const brokerListCache = createSearchParamsCache(brokerListParams);
export type BrokerListParams = Awaited<
  ReturnType<typeof brokerListCache.parse>
>;

export const brokerSchema = z.object({
  id: z.number().optional(),
  broker_name: z.string().min(1, "Name is required"),
  company_name: z.string().optional(),
  slug: z.string().optional(),
  broker_website: z.string().url().or(z.literal("")).optional(),
  overall_rating: z.string().optional(),
  description: z.string().optional(),
  headquarters: z.string().optional(),
  year_established: z.number().optional().nullable(),
  regulators: z.string().optional(),
  minimum_deposit: z.string().optional(),
  execution_types: z.string().optional(),
  trading_platforms: z.string().optional(),
  funding_methods: z.string().optional(),
  deposit_options: z.string().optional(),
  withdrawal_options: z.string().optional(),
  deposit_fees: z.string().optional(),
  withdrawal_fee: z.string().optional(),
  inactivity_fee: z.string().optional(),
  profit_share: z.string().optional(),
  retail_loss_rate: z.string().optional(),
  pros: z.string().optional(),
  cons: z.string().optional(),
  submitterName: z.string().optional(),
  submitterEmail: z.string().optional(),
  submitterNote: z.string().optional(),
  publishedAt: z.coerce.date().nullish(),
  status: z.enum(ToolStatus).default("Draft"),
  notifySubmitter: z.boolean().default(true),
  categoryIds: z.array(z.string()).optional(),
  subcategoryIds: z.array(z.string()).optional(),
  tagIds: z.array(z.string()).optional(),
  maximum_evaluation_fee: z.string().optional(),
  daily_loss_limit: z.string().optional(),
  minimum_raw_spreads: z.string().optional(),
  minimum_standard_spreads: z.string().optional(),
  minimum_commission_for_forex: z.string().optional(),
  average_trading_cost_eur_usd: z.string().optional(),
  average_trading_cost_gbp_usd: z.string().optional(),
  average_trading_cost_gold: z.string().optional(),
  average_trading_cost_bitcoin: z.string().optional(),
  average_trading_cost_wti_crude_oil: z.string().optional(),
  subtitle: z.string().optional(),
  screenshotUrl: z.string().url().or(z.literal("")).optional(),
  bannerUrl: z.string().url().or(z.literal("")).optional(),
  logoUrl: z.string().url().or(z.literal("")).optional(),
  typeId: z.string().nullish(),
  isSponsor: z.boolean().default(false),
  isMainSponsor: z.boolean().default(false),
  features: z.array(z.string()).optional(),
  socialProof: z.string().optional(),
  highlightedPoint: z.string().optional(),
  maxLeverage: z.string().optional(),
  totalInstruments: z.string().optional(),
  availableInIndia: z.boolean().default(false),
  islamicAccount: z.boolean().default(false),
  demoAccount: z.boolean().default(false),
  copyTrading: z.boolean().default(false),
  accountTypes: z.array(z.string()).optional(),
  beginner_friendly: z.boolean().default(false),
  review_article: z.string().optional(),
  seo_title: z.string().optional(),
  seo_meta_description: z.string().optional(),
  newer_traders_rating: z.number().optional().nullable(),
  scalpers_rating: z.number().optional().nullable(),
  swing_traders_rating: z.number().optional().nullable(),
  news_traders_rating: z.number().optional().nullable(),
  day_traders_rating: z.number().optional().nullable(),
  copy_traders_rating: z.number().optional().nullable(),
  automated_traders_rating: z.number().optional().nullable(),
  investors_rating: z.number().optional().nullable(),
  overall_review_rating: z.number().optional().nullable(),
  total_reviews: z.string().optional(),
  faqs: z
    .array(
      z.object({
        id: z.string().optional(),
        question: z.string().min(1, "Question is required"),
        answer: z.string().min(1, "Answer is required"),
      }),
    )
    .optional(),
  deployment_type: z.array(z.string()).optional(),
  starting_price: z.string().optional(),
  bestFor: z.array(z.string()).optional(),
  free_trial_available: z.boolean().optional().nullable(),
  api_access: z.boolean().optional().nullable(),
  support_channels: z.array(z.string()).optional(),
  support_hours: z.string().optional(),
  languages_supported: z.array(z.string()).optional(),
  pricingModel: z.array(z.string()).optional(),
  provider_type: z.array(z.string()).optional(),
  skill_level: z.array(z.string()).optional(),
  learning_format: z.array(z.string()).optional(),
  topics_covered: z.array(z.string()).optional(),
  outcomes: z.array(z.string()).optional(),
  certificate_available: z.boolean().optional().nullable(),
  community_access: z.boolean().optional().nullable(),
  mentorship_available: z.boolean().optional().nullable(),
  solution_type: z.string().optional(),
  target_clients: z.array(z.string()).optional(),
  asset_classes: z.array(z.string()).optional(),
  latency: z.string().optional(),
  white_label: z.boolean().optional().nullable(),
  setup_time: z.string().optional(),
  peak_capacity: z.string().optional(),
  global_hubs: z.array(z.string()).optional(),
  no_last_look: z.boolean().optional().nullable(),
  liquiditySources: z.array(z.string()).optional(),
  best_suited_for: z.array(z.string()).optional(),
  company_type: z.string().optional(),
  settlement_time: z.string().optional(),
  auto_fiat_conversion: z.boolean().optional().nullable(),
  kyb_required: z.boolean().optional().nullable(),
  supported_cryptos: z.string().optional(),
  fiat_currencies: z.string().optional(),
  integration_type: z.array(z.string()).optional(),
  mass_payout: z.boolean().optional().nullable(),
  checkout_page: z.boolean().optional().nullable(),
  platform_type: z.array(z.string()).optional(),
  prop_firm_support: z.array(z.string()).optional(),
  brokers_onboarded: z.string().optional(),
  trader_accounts: z.string().optional(),
  white_label_price: z.string().optional(),
  server_license: z.string().optional(),
  charting_tools: z.array(z.string()).optional(),
  mt5_backend: z.boolean().optional().nullable(),
  yearly_commitment: z.boolean().optional().nullable(),
  clients_count: z.string().optional(),
  hosting_included: z.boolean().optional().nullable(),
  crm_integrations: z.string().optional(),
  liquidity_connect: z.string().optional(),
  kyc_compliance: z.string().optional(),
  verified_performance: z.string().optional(),
  bot_type: z.string().optional(),
  strategy_type: z.array(z.string()).optional(),
  risk_levels: z.array(z.string()).optional(),
  win_rate: z.string().optional(),
  trades_per_day: z.string().optional(),
  supported_pairs: z.array(z.string()).optional(),
  nfa_fifo: z.boolean().optional().nullable(),
  ecn_compatible: z.boolean().optional().nullable(),
  vps_required: z.boolean().optional().nullable(),
  mobile_support: z.boolean().optional().nullable(),
  gold_plan_price: z.string().optional(),
  gold_plan_statements: z.array(z.string()).optional(),
  diamond_plan_price: z.string().optional(),
  diamond_plan_statements: z.array(z.string()).optional(),
  automation_level: z.string().optional(),
  courseModules: z
    .array(
      z.object({
        id: z.number().optional(),
        title: z.string().min(1, "Title is required"),
        difficulty: z.enum(["Beginner", "Intermediate", "Advanced"]),
        duration: z.string().min(1, "Duration is required"),
        topics: z.array(z.string()).optional(),
        order: z.number().optional(),
      }),
    )
    .optional(),
  reviews: z
    .array(
      z.object({
        id: z.string().optional(),
        reviewer_name: z.string().nullable().optional(),
        reviewer_location: z.string().nullable().optional(),
        review_rat: z.string().nullable().optional(),
        review_description: z.string().nullable().optional(),
        createdAt: z.date().nullable().optional(),
        updatedAt: z.date().nullable().optional(),
      }),
    )
    .optional(),
});

export type BrokerSchema = z.infer<typeof brokerSchema>;
