-- CreateTable
CREATE TABLE "forex_brokers" (
    "id" SERIAL NOT NULL,
    "average_trading_cost_bitcoin" VARCHAR(82),
    "average_trading_cost_eur_usd" VARCHAR(95),
    "average_trading_cost_gbp_usd" VARCHAR(95),
    "average_trading_cost_gold" VARCHAR(92),
    "average_trading_cost_wti_crude_oil" VARCHAR(92),
    "broker_name" VARCHAR(50),
    "cons" TEXT,
    "daily_loss_limit" VARCHAR(44),
    "deposit_options" VARCHAR(111),
    "description" TEXT,
    "execution_types" VARCHAR(65),
    "funded_account_options" VARCHAR(66),
    "funding_methods" VARCHAR(213),
    "headquarters" VARCHAR(63),
    "maximum_funded_account" VARCHAR(48),
    "maximum_trailing_drawdown" VARCHAR(29),
    "minimum_commission_for_forex" VARCHAR(101),
    "minimum_deposit" VARCHAR(68),
    "minimum_evaluation_fee" VARCHAR(37),
    "minimum_funded_account" VARCHAR(27),
    "minimum_raw_spreads" VARCHAR(46),
    "minimum_standard_spreads" VARCHAR(34),
    "mobile_app_comparison" TEXT,
    "other_fees" TEXT,
    "overall_rating" VARCHAR(25),
    "profit_share" VARCHAR(44),
    "pros" TEXT,
    "regulators" VARCHAR(88),
    "regulators_table" TEXT,
    "retail_loss_rate" VARCHAR(49),
    "scraped_at" TIMESTAMP(6),
    "trader_table" TEXT,
    "trading_hours" TEXT,
    "trading_platforms" VARCHAR(98),
    "url" VARCHAR(98),
    "withdrawal_options" VARCHAR(111),
    "year_established" DOUBLE PRECISION,

    CONSTRAINT "forex_brokers_pkey" PRIMARY KEY ("id")
);
