import { db } from "../services/db"

async function main() {
  // Pass your array of objects here!
const brokers=   [
  {
    "id": "cmmumll8200030bldd3h6ihga",
    "name": "Your Bourse",
    "slug": "your-bourse",
    "websiteUrl": "https://www.yourbourse.com",
    "logoUrl": "https://fxdirs.sfo3.digitaloceanspaces.com/sponsors/your-bourse/logo.png",
    "categoryId": "cmmui1v8e0003thl9ielaeif1",
    "description": "Premium Platform-as-a-Service for FX, CFD, and crypto liquidity management and data analytics.",
    "headquarters": "Tallinn, Estonia",
    "year_established": 2017,
    "status": "Published",
    "pros": "Ultra-low latency, 24/7 support, plug-and-play for MT4/MT5",
    "cons": "Institutional focus only",
    "overall_rating": "4.9",
    "trading_platforms": "MT4, MT5, FIX API",
    "execution_types": "Bridge / Aggregator",
    "regulators": "EU Registered",
    "isActive": true
  },
  {
    "id": "cmmumjbut00020bldq0nc2xqr",
    "name": "Tools for Brokers",
    "slug": "tools-for-brokers",
    "websiteUrl": "https://t4b.com",
    "logoUrl": "https://fxdirs.sfo3.digitaloceanspaces.com/sponsors/tools-for-brokers/logo.png",
    "categoryId": "cmmui1v8e0003thl9ielaeif1",
    "description": "Technology provider offering liquidity bridges, risk management, and data management for MT4/MT5 brokers.",
    "headquarters": "Limassol, Cyprus",
    "year_established": 2009,
    "status": "Published",
    "pros": "Extensive plugin library, Deep MetaTrader expertise",
    "cons": "Steep learning curve for new operators",
    "overall_rating": "4.8",
    "trading_platforms": "MT4, MT5, cTrader",
    "execution_types": "Bridge / Risk Management",
    "regulators": "CySEC (Tech)",
    "isActive": true
  },
  {
    "id": "cmmumcfea00010bld1aipcl48",
    "name": "FxCubic",
    "slug": "fxcubic",
    "websiteUrl": "https://fxcubic.com",
    "logoUrl": "https://fxdirs.sfo3.digitaloceanspaces.com/sponsors/fxcubic/logo.png",
    "categoryId": "cmmui1v8e0003thl9ielaeif1",
    "description": "Low-latency pricing and liquidity aggregation engine for institutional and retail brokers.",
    "headquarters": "London, UK",
    "year_established": 2017,
    "status": "Published",
    "pros": "High-performance routing, Multi-platform support",
    "cons": "Requires technical team to manage",
    "overall_rating": "4.7",
    "trading_platforms": "API, MT4, MT5",
    "execution_types": "Liquidity Aggregator",
    "isActive": true
  },
  {
    "id": "cmmum26b100000bldwpc7oa62",
    "name": "Centroid Sol",
    "slug": "centroid-solutions",
    "websiteUrl": "https://centroidsol.com/",
    "logoUrl": "https://fxdirs.sfo3.digitaloceanspaces.com/sponsors/centroid-solutions/logo.png",
    "categoryId": "cmmui1v8e0003thl9ielaeif1",
    "description": "Specializing in risk management, analytics, and complex execution routing for multi-asset brokers.",
    "headquarters": "Dubai, UAE",
    "year_established": 2017,
    "status": "Published",
    "pros": "Advanced risk analytics, Real-time monitoring",
    "cons": "Complex pricing models",
    "overall_rating": "4.8",
    "trading_platforms": "FIX API, MT4, MT5",
    "execution_types": "Risk Engine / Bridge",
    "isActive": true
  },
  {
    "id": "cmmultrdl00080ajp0stpph1q",
    "name": "Techysquad",
    "slug": "techysquad",
    "websiteUrl": "https://techysquad.com/",
    "logoUrl": "https://fxdirs.sfo3.digitaloceanspaces.com/sponsors/techysquad/logo.png",
    "categoryId": "cmmg85gcn0004tml97wuv5wec",
    "description": "Comprehensive CRM and back-office solutions specifically designed for the Forex and CFD industry.",
    "headquarters": "Dubai, UAE",
    "year_established": 2015,
    "status": "Published",
    "pros": "Affordable, Fast deployment, Built-in IB portal",
    "cons": "Interface is less modern than competitors",
    "overall_rating": "4.5",
    "trading_platforms": "CRM Integration",
    "isActive": true
  },
  {
    "id": "cmmulnq7d00070ajpk1ye98qr",
    "name": "FXBO",
    "slug": "fxbo",
    "websiteUrl": "https://fxbackoffice.com/",
    "logoUrl": "https://fxdirs.sfo3.digitaloceanspaces.com/sponsors/fxbo/logo.png",
    "categoryId": "cmmg85gcn0004tml97wuv5wec",
    "description": "Advanced CRM and Back Office management system with a focus on automation and high-level reporting.",
    "headquarters": "Limassol, Cyprus",
    "year_established": 2017,
    "status": "Published",
    "pros": "300+ PSP integrations, Highly customizable",
    "cons": "Premium pricing tier",
    "overall_rating": "4.9",
    "trading_platforms": "All Major Platforms",
    "isActive": true
  },
  {
    "id": "cmmulhpd500060ajp3kmt9bju",
    "name": "UpTrader",
    "slug": "uptrader",
    "websiteUrl": "https://uptrader.io/",
    "logoUrl": "https://fxdirs.sfo3.digitaloceanspaces.com/sponsors/uptrader/logo.png",
    "categoryId": "cmmg85gcn0004tml97wuv5wec",
    "description": "Cloud-based CRM and social trading software solutions for retail and institutional brokers.",
    "headquarters": "Limassol, Cyprus",
    "year_established": 2015,
    "status": "Published",
    "pros": "Excellent Copy-Trading module, Easy setup",
    "cons": "Limited deep-level API customization",
    "overall_rating": "4.6",
    "trading_platforms": "MT4, MT5",
    "isActive": true
  },
  {
    "id": "cmmuld5xg00050ajpmmswbd0t",
    "name": "FYNXT",
    "slug": "fynxt",
    "websiteUrl": "https://fynxt.com/",
    "logoUrl": "https://fxdirs.sfo3.digitaloceanspaces.com/sponsors/fynxt/logo.png",
    "categoryId": "cmmg85gcn0004tml97wuv5wec",
    "description": "Low-code financial services infrastructure for multi-asset brokers and wealth managers.",
    "headquarters": "Singapore",
    "year_established": 2018,
    "status": "Published",
    "pros": "Modern UI, Highly modular, Strong security",
    "cons": "Newer entrant in European markets",
    "overall_rating": "4.7",
    "trading_platforms": "API Driven",
    "isActive": true
  },
  {
    "id": "cmmul8vpx00010ajp1s7fs3wz",
    "name": "Skale CRM",
    "slug": "skale-crm",
    "websiteUrl": "https://www.skalecrm.com/",
    "logoUrl": "https://fxdirs.sfo3.digitaloceanspaces.com/sponsors/skale-crm/logo.png",
    "categoryId": "cmmg85gcn0004tml97wuv5wec",
    "description": "Enterprise-grade CRM with advanced KYC orchestration and multi-tenant IB modules.",
    "headquarters": "London, UK",
    "year_established": 2020,
    "status": "Published",
    "pros": "KYC automation, Built for high volume",
    "cons": "Enterprise focus makes it pricey for startups",
    "overall_rating": "4.8",
    "trading_platforms": "MT4, MT5, cTrader",
    "isActive": true
  },
  {
    "id": "cmmul39n200000ajp3kzedayo",
    "name": "Praxis",
    "slug": "praxis",
    "websiteUrl": "https://praxis.tech/",
    "logoUrl": "https://fxdirs.sfo3.digitaloceanspaces.com/sponsors/praxis/logo.png",
    "categoryId": "cmmui0xq10002thl9usal9bll",
    "description": "A payment orchestration software designed to streamline global payment processing and routing.",
    "headquarters": "Limassol, Cyprus",
    "year_established": 2014,
    "status": "Published",
    "pros": "Unmatched PSP network, Intelligent routing",
    "cons": "Complex integration process",
    "overall_rating": "4.9",
    "deposit_options": "300+ Local & Global Methods",
    "regulators": "PCI DSS Level 1",
    "isActive": true
  },
  {
    "id": "cmmukp0id00010al260kqgi48",
    "name": "Match2Pay",
    "slug": "match2pay",
    "websiteUrl": "https://match2pay.com/",
    "logoUrl": "https://fxdirs.sfo3.digitaloceanspaces.com/sponsors/match2pay/logo.png",
    "categoryId": "cmmui0xq10002thl9usal9bll",
    "description": "Crypto payment gateway for forex brokers and merchants, offering instant settlements.",
    "headquarters": "Warsaw, Poland",
    "year_established": 2019,
    "status": "Published",
    "pros": "Automated reconciliation, High security",
    "cons": "Restricted to crypto-native payments",
    "overall_rating": "4.6",
    "deposit_options": "BTC, ETH, USDT, USDC",
    "isActive": true
  },
  {
    "id": "cmmukkfzm00000al2zxgilhuv",
    "name": "Pay Me",
    "slug": "pay-me",
    "websiteUrl": "https://payme.io",
    "logoUrl": "https://fxdirs.sfo3.digitaloceanspaces.com/sponsors/pay-me/logo.png",
    "categoryId": "cmmui0xq10002thl9usal9bll",
    "description": "Regional payment gateway focusing on emerging market local payment solutions.",
    "headquarters": "Hong Kong",
    "year_established": 2017,
    "status": "Published",
    "pros": "Strong in SE Asia and Africa, Low fees",
    "cons": "Limited European coverage",
    "overall_rating": "4.4",
    "deposit_options": "E-wallets, Local Transfers",
    "isActive": true
  },
  {
    "id": "cmmuk1doz00010al9fxzib2id",
    "name": "UniPayment",
    "slug": "unipayment",
    "websiteUrl": "https://unipayment.io/",
    "logoUrl": "https://fxdirs.sfo3.digitaloceanspaces.com/sponsors/unipayment/logo.png",
    "categoryId": "cmmui0xq10002thl9usal9bll",
    "description": "B2B crypto payment solution provider specializing in automatic fiat conversions for businesses.",
    "headquarters": "London, UK",
    "year_established": 2021,
    "status": "Published",
    "pros": "Fast fiat off-ramping, Low fees",
    "cons": "Regulatory requirements vary by region",
    "overall_rating": "4.5",
    "deposit_options": "50+ Cryptocurrencies",
    "isActive": true
  },
  {
    "id": "cmmujwzbr00000al9hts9oy23",
    "name": "Cregis",
    "slug": "cregis",
    "websiteUrl": "https://www.cregis.com",
    "logoUrl": "https://fxdirs.sfo3.digitaloceanspaces.com/sponsors/cregis/logo.png",
    "categoryId": "cmmui0xq10002thl9usal9bll",
    "description": "Web3 payment infrastructure with enterprise-grade MPC wallet security for digital asset management.",
    "headquarters": "Singapore",
    "year_established": 2018,
    "status": "Published",
    "pros": "MPC security, Multi-user approval flows",
    "cons": "Targeted at tech-savvy brokers",
    "overall_rating": "4.6",
    "deposit_options": "Digital Assets",
    "isActive": true
  },
  {
    "id": "cmmuj9i3200010ajy9lvsixi2",
    "name": "Finalto",
    "slug": "finalto",
    "websiteUrl": "https://finalto.com/",
    "logoUrl": "https://fxdirs.sfo3.digitaloceanspaces.com/sponsors/XSURznrnWuvv/logo.png",
    "categoryId": "cmmuhzqte0001thl9f0opbof0",
    "description": "Global multi-asset liquidity provider offering bespoke tech and prime brokerage services.",
    "headquarters": "London, UK",
    "year_established": 2008,
    "status": "Published",
    "pros": "Institutional grade, FCA regulated, Massive asset list",
    "cons": "Not available to retail direct",
    "overall_rating": "4.9",
    "trading_platforms": "ClearPro, FIX API",
    "execution_types": "Market Maker / STP",
    "regulators": "FCA, ASIC, CySEC",
    "isActive": true
  },
  {
    "id": "cmmuiuk5t00000al7bv1aeiz5",
    "name": "LMAX Group",
    "slug": "lmax-group",
    "websiteUrl": "https://www.lmax.com/",
    "logoUrl": "https://fxdirs.sfo3.digitaloceanspaces.com/sponsors/dcXlLtq8xPHp/logo.png",
    "categoryId": "cmmuhzqte0001thl9f0opbof0",
    "description": "Leading operator of institutional execution venues for global FX and digital asset trading.",
    "headquarters": "London, UK",
    "year_established": 2010,
    "status": "Published",
    "pros": "No 'last look' execution, Central limit order book",
    "cons": "Strict onboarding for smaller brokers",
    "overall_rating": "4.9",
    "trading_platforms": "LMAX UI, FIX API",
    "execution_types": "Exchange Model / ECN",
    "regulators": "FCA, CySEC",
    "isActive": true
  },
  {
    "id": "cmmuipd4a00000ajoziei4f3e",
    "name": "Match-Trader",
    "slug": "match-trader",
    "websiteUrl": "https://match-trader.com/",
    "logoUrl": "https://fxdirs.sfo3.digitaloceanspaces.com/sponsors/match-trader/logo.png",
    "categoryId": "cmmuhxrq50000thl9k3vtir0y",
    "description": "Modern, white-label trading platform with built-in client office and prop-firm features.",
    "headquarters": "Warsaw, Poland",
    "year_established": 2013,
    "status": "Published",
    "pros": "Best for Prop Firms, All-in-one ecosystem",
    "cons": "Lower user familiarity than MetaTrader",
    "overall_rating": "4.7",
    "trading_platforms": "Match-Trader Desktop/Mobile",
    "execution_types": "Broker-defined",
    "isActive": true
  },
  {
    "id": "cmmuigatc0004thl9b31xeki0",
    "name": "cTrader",
    "slug": "ctrader",
    "websiteUrl": "https://ctrader.com/",
    "logoUrl": "https://fxdirs.sfo3.digitaloceanspaces.com/sponsors/ctrader/logo.png",
    "categoryId": "cmmuhxrq50000thl9k3vtir0y",
    "description": "Advanced trading platform known for transparency, ECN execution, and C#-based algorithmic trading.",
    "headquarters": "Limassol, Cyprus",
    "year_established": 2010,
    "status": "Published",
    "pros": "Superb charting, Native copy trading, Mobile-first",
    "cons": "Smallest library of 3rd party bots vs MT4",
    "overall_rating": "4.9",
    "trading_platforms": "cTrader Suite",
    "execution_types": "ECN / STP",
    "isActive": true
  },
  {
    "id": "cmm31rt5q000dnhl9i66iffkl",
    "name": "Golden Bulls International",
    "slug": "golden-bulls-international",
    "websiteUrl": "http://goldenbulls.international/",
    "logoUrl": "https://fxdirs.sfo3.digitaloceanspaces.com/sponsors/golden-bulls-international/logo.png",
    "categoryId": "cmmg85ful0001tml95ubdraqc",
    "description": "Educational academy focusing on elite mentorship and technical market analysis.",
    "headquarters": "Dubai, UAE",
    "year_established": 2020,
    "status": "Published",
    "pros": "1-on-1 coaching, High success rate",
    "cons": "Premium price point",
    "overall_rating": "4.3",
    "isActive": true
  },
  {
    "id": "cmm31q2r1000cnhl95yy425kt",
    "name": "Edufins",
    "slug": "edufins",
    "websiteUrl": "https://www.edufins.com/",
    "logoUrl": "https://fxdirs.sfo3.digitaloceanspaces.com/sponsors/edufins/logo.png",
    "categoryId": "cmmg85ful0001tml95ubdraqc",
    "description": "Online financial platform offering comprehensive courses for retail traders of all levels.",
    "headquarters": "UK",
    "year_established": 2021,
    "status": "Published",
    "pros": "Structured curriculum, Community access",
    "cons": "Self-paced can be slow for some",
    "overall_rating": "4.5",
    "isActive": true
  },
  {
    "id": "cmm31lqf8000bnhl9ya1vqm8b",
    "name": "PipGrid",
    "slug": "pipgrid",
    "websiteUrl": "https://pipgrid.com/",
    "logoUrl": "https://fxdirs.sfo3.digitaloceanspaces.com/sponsors/pipgrid/logo.webp",
    "categoryId": "cmmg85g0n0002tml9so3x5w9d",
    "description": "Specialized grid-based algorithmic trading tools for the MetaTrader 4 and 5 environments.",
    "headquarters": "Remote",
    "year_established": 2022,
    "status": "Published",
    "pros": "Set-and-forget logic, Consistent performance",
    "cons": "High risk in trending markets",
    "overall_rating": "4.2",
    "trading_platforms": "MT4, MT5",
    "isActive": true
  },
  {
    "id": "cmm31iwhc000anhl9vti1szbb",
    "name": "MakeMyProfits",
    "slug": "makemyprofits",
    "websiteUrl": "https://makemyprofits.com/",
    "logoUrl": "https://fxdirs.sfo3.digitaloceanspaces.com/sponsors/makemyprofits/logo.png",
    "categoryId": "cmmg85g0n0002tml9so3x5w9d",
    "description": "Subscription-based signal and bot service focused on automated gold and FX trading.",
    "headquarters": "Remote",
    "year_established": 2021,
    "status": "Published",
    "pros": "Good historical data, User dashboard",
    "cons": "Signals can be delayed",
    "overall_rating": "4.0",
    "trading_platforms": "MT4, MT5",
    "isActive": true
  },
  {
    "id": "cmm31gh320009nhl9revjk87l",
    "name": "Lunarwolf",
    "slug": "lunarwolf",
    "websiteUrl": "https://lunarwolf.ai/",
    "logoUrl": "https://fxdirs.sfo3.digitaloceanspaces.com/sponsors/lunarwolf/logo.webp",
    "categoryId": "cmmg85g0n0002tml9so3x5w9d",
    "description": "AI-driven predictive market models and high-frequency automated trading scripts.",
    "headquarters": "USA",
    "year_established": 2023,
    "status": "Published",
    "pros": "Cutting edge AI, Proprietary indicators",
    "cons": "Expensive monthly fees",
    "overall_rating": "4.4",
    "trading_platforms": "API, MT5",
    "isActive": true
  },
  {
    "id": "cmm31ecmz0008nhl9nvqnbeol",
    "name": "Algomatic Bot",
    "slug": "algomatic-bot",
    "websiteUrl": "https://algomaticbot.com",
    "logoUrl": "https://fxdirs.sfo3.digitaloceanspaces.com/sponsors/algomatic-bot/logo.png",
    "categoryId": "cmmg85g0n0002tml9so3x5w9d",
    "description": "Robo-advisor and automated EA marketplace for retail forex traders.",
    "headquarters": "Remote",
    "year_established": 2021,
    "status": "Published",
    "pros": "Low cost entry, Community backed",
    "cons": "Variable strategy quality",
    "overall_rating": "4.1",
    "trading_platforms": "MT4",
    "isActive": true
  },
  {
    "id": "cmm31bmno0007nhl9oa60t2u9",
    "name": "ExoraPrime",
    "slug": "exoraprime",
    "websiteUrl": "https://www.exoraprime.com/",
    "logoUrl": "https://fxdirs.sfo3.digitaloceanspaces.com/sponsors/exoraprime/logo.png",
    "categoryId": "cmmg85em10000tml982kky6je",
    "description": "Retail broker offering raw spreads, institutional execution, and top-tier client security.",
    "headquarters": "St. Vincent & Grenadines",
    "year_established": 2022,
    "status": "Published",
    "pros": "High leverage, Raw spreads, Instant execution",
    "cons": "Offshore regulation",
    "overall_rating": "4.2",
    "trading_platforms": "MT5",
    "execution_types": "ECN / STP",
    "minimum_deposit": "$50",
    "leverage_options": "Up to 1:500",
    "minimum_raw_spreads": "0.0 pips",
    "regulators": "FSA (SVG)",
    "isActive": true
  },
  {
    "id": "cmm319tac0006nhl9dcd0b2jv",
    "name": "SeaGlobalFX",
    "slug": "seaglobalfx",
    "websiteUrl": "https://seaglobalfx.com/",
    "logoUrl": "https://fxdirs.sfo3.digitaloceanspaces.com/sponsors/seaglobalfx/logo.png",
    "categoryId": "cmmg85em10000tml982kky6je",
    "description": "Multi-asset broker providing global market access with advanced trading infrastructure.",
    "headquarters": "St. Vincent & Grenadines",
    "year_established": 2021,
    "status": "Published",
    "pros": "Fast account opening, Multi-currency funding",
    "cons": "Limited education section",
    "overall_rating": "4.1",
    "trading_platforms": "MT5",
    "minimum_deposit": "$100",
    "leverage_options": "1:400",
    "regulators": "FSA (SVG)",
    "isActive": true
  },
  {
    "id": "cmm315x030005nhl97xwxqe7s",
    "name": "Blueberry Markets",
    "slug": "blueberry-markets",
    "websiteUrl": "https://blueberrymarkets.com/",
    "logoUrl": "https://fxdirs.sfo3.digitaloceanspaces.com/sponsors/blueberry-markets/logo.png",
    "categoryId": "cmmg85em10000tml982kky6je",
    "description": "Industry-leading Australian broker known for low costs and dedicated account managers.",
    "headquarters": "Sydney, Australia",
    "year_established": 2016,
    "status": "Published",
    "pros": "ASIC Regulated, Exceptional support, Tight spreads",
    "cons": "No crypto funding for some regions",
    "overall_rating": "4.8",
    "trading_platforms": "MT4, MT5",
    "execution_types": "ECN",
    "minimum_deposit": "$100",
    "leverage_options": "Up to 1:30 (AU) / 1:500 (Global)",
    "minimum_raw_spreads": "0.0 pips",
    "regulators": "ASIC, SCB",
    "isActive": true
  },
  {
    "id": "cmm312do00004nhl93km27qe6",
    "name": "SecureFX",
    "slug": "securefx",
    "websiteUrl": "https://www.securefx.net/",
    "logoUrl": "https://fxdirs.sfo3.digitaloceanspaces.com/sponsors/securefx/logo.png",
    "categoryId": "cmmg85em10000tml982kky6je",
    "description": "Forex and CFD broker providing high-speed execution and enhanced security features.",
    "headquarters": "Vanuatu",
    "year_established": 2019,
    "status": "Published",
    "pros": "Negative balance protection, Easy funding",
    "cons": "Smaller range of CFD assets",
    "overall_rating": "4.0",
    "trading_platforms": "MT4",
    "minimum_deposit": "$10",
    "leverage_options": "1:500",
    "regulators": "VFSC",
    "isActive": true
  },
  {
    "id": "cmm310q850003nhl954lmo80a",
    "name": "Winprofx",
    "slug": "winprofx",
    "websiteUrl": "https://winprofx.com",
    "logoUrl": "https://fxdirs.sfo3.digitaloceanspaces.com/sponsors/winprofx/logo.png",
    "categoryId": "cmmg85em10000tml982kky6je",
    "description": "ECN broker focusing on deep liquidity and low-cost trading environments for scalpers.",
    "headquarters": "Dubai, UAE",
    "year_established": 2020,
    "status": "Published",
    "pros": "Dubai presence, Local support, Deep liquidity",
    "cons": "Platform maintenance can be frequent",
    "overall_rating": "4.2",
    "trading_platforms": "MT5",
    "minimum_deposit": "$100",
    "leverage_options": "1:500",
    "isActive": true
  },
  {
    "id": "cmm30vh8j0002nhl9ep2aqfd3",
    "name": "Skyriss",
    "slug": "skyriss",
    "websiteUrl": "https://www.skyriss.com",
    "logoUrl": "https://fxdirs.sfo3.digitaloceanspaces.com/sponsors/skyriss/logo.webp",
    "categoryId": "cmmg85em10000tml982kky6je",
    "description": "Modern multi-asset broker with a focus on institutional-grade connectivity for retail traders.",
    "headquarters": "Mauritius",
    "year_established": 2022,
    "status": "Published",
    "pros": "Institutional execution, No Last Look",
    "cons": "New brand, short track record",
    "overall_rating": "4.3",
    "trading_platforms": "MT5, FIX API",
    "regulators": "FSC (Mauritius)",
    "isActive": true
  },
  {
    "id": "cmm30sk6u0001nhl9jrjgbiss",
    "name": "The Crib Market",
    "slug": "the-crib-market",
    "websiteUrl": "https://thecribmarket.com/",
    "logoUrl": "https://fxdirs.sfo3.digitaloceanspaces.com/sponsors/the-crib-market/logo.png",
    "categoryId": "cmmg85em10000tml982kky6je",
    "description": "Community-focused broker offering social trading features and specialized mentorship access.",
    "headquarters": "South Africa",
    "year_established": 2021,
    "status": "Published",
    "pros": "Strong in African markets, Social-first approach",
    "cons": "Limited global regulation",
    "overall_rating": "4.4",
    "trading_platforms": "WebTrader, MT4",
    "regulators": "FSCA",
    "isActive": true
  },
  {
    "id": "cmm301vmb0000nhl9j2v5rr8u",
    "name": "Newera365",
    "slug": "newera365",
    "websiteUrl": "https://newera365.com/",
    "logoUrl": "https://fxdirs.sfo3.digitaloceanspaces.com/sponsors/48PU1gns9zx5/logo.webp",
    "categoryId": "cmmg85em10000tml982kky6je",
    "description": "Modern brokerage designed for the 24/7 digital era, focusing on FX and crypto assets.",
    "headquarters": "Seychelles",
    "year_established": 2023,
    "status": "Published",
    "pros": "High-speed crypto funding, MT5 specialized",
    "cons": "Minimal historical performance data",
    "overall_rating": "4.0",
    "trading_platforms": "MT5",
    "regulators": "FSA (Seychelles)",
    "isActive": true
  }
]
  for (const data of brokers) {
    try {
      const result = await db.brokers.upsert({
        where: { slug: data.slug },
        update: {
          broker_name: data.name,
          broker_website: data.websiteUrl,
          screenshotUrl: data.logoUrl,
          description: data.description,
          headquarters: data.headquarters,
          year_established: data.year_established,
          status: data.status as any,
          pros: data.pros,
          cons: data.cons,
          overall_rating: data.overall_rating,
          trading_platforms: data.trading_platforms,
          execution_types: data.execution_types,
          regulators: data.regulators,
          isSponsor: data.isActive,
          categories: data.categoryId ? {
            set: [{ id: data.categoryId }]
          } : undefined
        },
        create: {
          broker_name: data.name,
          slug: data.slug,
          broker_website: data.websiteUrl,
          screenshotUrl: data.logoUrl,
          description: data.description,
          headquarters: data.headquarters,
          year_established: data.year_established,
          status: data.status as any,
          pros: data.pros,
          cons: data.cons,
          overall_rating: data.overall_rating,
          trading_platforms: data.trading_platforms,
          execution_types: data.execution_types,
          regulators: data.regulators,
          isSponsor: data.isActive,
          categories: data.categoryId ? {
            connect: [{ id: data.categoryId }]
          } : undefined
        }
      })
      console.log("Successfully upserted broker:", result.broker_name)
    } catch (error) {
      console.error(`Error upserting broker ${data.name}:`, error)
    }
  }
}

main()
